FROM isaudits/kali:base

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends metasploit-framework && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* &&\
    service postgresql start && \
    msfdb init && \
    service postgresql stop