#!/bin/bash
set -ueo pipefail

docker buildx build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --platform linux/amd64,linux/arm64 \
             --push -t isaudits/kali:base -t isaudits/kali:latest .
             
docker buildx build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --platform linux/amd64,linux/arm64 \
             --push -t isaudits/kali:msf -f Dockerfile.msf .

docker buildx build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --platform linux/amd64,linux/arm64 \
             --push -t isaudits/kali:xfce -f Dockerfile.xfce .